# fly.toml app configuration file generated for icd-search-white-glitter-5169 on 2024-03-20T17:12:41+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'icd-search'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
